[121.000766754] 2018-06-25 15:14:43,590 - INFO - launcher: Starting sanity checks
[131.000757217] 2018-06-25 15:14:43,600 - INFO - launcher: Checking for Python 3.5+
[131.000757217] 2018-06-25 15:14:43,600 - INFO - launcher: Checking console encoding
[131.000757217] 2018-06-25 15:14:43,600 - INFO - launcher: Setting console encoding to UTF-8
[131.000757217] 2018-06-25 15:14:43,600 - INFO - launcher: Ensuring we're in the right environment
[131.000757217] 2018-06-25 15:14:43,600 - INFO - launcher: Adding local bins/ folder to path
[141.000747681] 2018-06-25 15:14:43,610 - INFO - launcher: Required checks passed.
[141.000747681] 2018-06-25 15:14:43,610 - INFO - launcher: Optional checks passed.
[141.000747681] 2018-06-25 15:14:43,610 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[3.5270967483520508] 2018-06-25 15:14:46,996 - WARNING - musicbot.config | In config.py::MainThread(4108), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[3.5270967483520508] 2018-06-25 15:14:46,996 - INFO - musicbot.config | In config.py::MainThread(4108), line 123 in run_checks: Using i18n: config/i18n/en.json
[3.5270967483520508] 2018-06-25 15:14:46,996 - WARNING - musicbot.config | In config.py::MainThread(4108), line 293 in find_autoplaylist: No autoplaylist file found.
[3.5410971641540527] 2018-06-25 15:14:47,010 - DEBUG - musicbot.json | In json.py::MainThread(4108), line 8 in __init__: Init JSON obj with config/i18n/en.json
[4.6031169891357422] 2018-06-25 15:14:48,072 - DEBUG - musicbot.bot | In bot.py::MainThread(4108), line 227 in _setup_logging: Set logging level to INFO
[4.6031169891357422] 2018-06-25 15:14:48,072 - INFO - musicbot.bot | In bot.py::MainThread(4108), line 84 in __init__: Starting MusicBot 1.9.7
[4.6031169891357422] 2018-06-25 15:14:48,072 - WARNING - musicbot.bot | In bot.py::MainThread(4108), line 87 in __init__: Autoplaylist is empty, disabling.
[5.175137997] launcher-INFO: 
An error has occured:
  Problem:
    Bot cannot login, bad credentials.

  Solution:
    Fix your token in the options file.  Remember that each field should be on
    their own line.


[5.179138422] launcher-INFO: All done.
